### ISSUE TITLE
三级证书验证失败

### ISSUE THREAD

**Issue by yudaowen** [WeBankBlockchain/Governance-Cert#25]
certChain.add(rootCertificate);
certChain.add(childCertificate);
certChain.add(thiredCertificate);
System.out.println();
System.out.println("证书链验证结果 = " + certService.verify(rootCertificate,certChain));

false

**Comment by wangyue168git** [comment]
麻烦提供下更详细的信息看下，可以在三级证书中增加前两级证书的信息
